#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-lambda.r
Version  : 1.2.2
Release  : 14
URL      : https://cran.r-project.org/src/contrib/lambda.r_1.2.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lambda.r_1.2.2.tar.gz
Summary  : Modeling Data with Functional Programming
Group    : Development/Tools
License  : LGPL-3.0
Requires: R-formatR
BuildRequires : R-formatR
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n lambda.r

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524275243

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1524275243
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lambda.r
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lambda.r
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lambda.r
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library lambda.r|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lambda.r/DESCRIPTION
/usr/lib64/R/library/lambda.r/INDEX
/usr/lib64/R/library/lambda.r/Meta/Rd.rds
/usr/lib64/R/library/lambda.r/Meta/features.rds
/usr/lib64/R/library/lambda.r/Meta/hsearch.rds
/usr/lib64/R/library/lambda.r/Meta/links.rds
/usr/lib64/R/library/lambda.r/Meta/nsInfo.rds
/usr/lib64/R/library/lambda.r/Meta/package.rds
/usr/lib64/R/library/lambda.r/NAMESPACE
/usr/lib64/R/library/lambda.r/R/lambda.r
/usr/lib64/R/library/lambda.r/R/lambda.r.rdb
/usr/lib64/R/library/lambda.r/R/lambda.r.rdx
/usr/lib64/R/library/lambda.r/help/AnIndex
/usr/lib64/R/library/lambda.r/help/aliases.rds
/usr/lib64/R/library/lambda.r/help/lambda.r.rdb
/usr/lib64/R/library/lambda.r/help/lambda.r.rdx
/usr/lib64/R/library/lambda.r/help/paths.rds
/usr/lib64/R/library/lambda.r/html/00Index.html
/usr/lib64/R/library/lambda.r/html/R.css
